exports.messages = 
{
    TRUE : 1,
    FALSE : 0,
    JWT_STRING : "Gamerji",
    DESCRIPTION:"description required",
    DATA_ADD_SUCCESSFULLY : "data added successfully..!",
    DATA_UPDATE_SUCCESSFULLY : "data updated successfully..!",
    DATA_DELETE_SUCCESSFULLY : "data deleted successfully..!",
    DATA_GET_SUCCESSFULLY : "data get successfully..!",
    SOMETHING_WENT_WRONG : "something went's wrong..!",
    USER_NOT_EXISTS : "user not exists..!",
    EMAIL_OR_NUMBER : "Email or number is required..!",
    NUMBER : "Mobile number is required..!",
    OTP_VERIFY : "otp verify successfully..!",
    OTP_NOT_EXISTS : "Invalide OTP!",
    MOBILE_VERIFYED : "mobile number is verifyed..!",
    MOBILE_NOTVERIFYED : "mobile number is not verifyed..!",
    EMAIL_VERIFYED : "email id is verifyed..!",
    EMAIL_NOTVERIFYED : "email id is not verifyed..!",
    USER_REGISTER_NOT: "you are not valid user..!",
    USER_REGISTER :"Your registration has been successfully. Once admin approve your request, then you can able to sign in..!",
    LOGIN_SUCCESS : "login successfully..!",
    INFO_NOT_FOUND:"Information not found.",
    IS_REQUIRED : " is required..!",
    USER_EXIST:"email or number is already exist.",
    MISMATCH_UUID:"User identification mismatch",
    UPLOAD_ERROR:"Please upload a valid file.",
    REQUESTED_ADMIN:"Admin approval required, Please contact admin.",
    REGISTRATION_REQUIRE:"Not registered user, Please register.",
    UPDATE_REQUESTED:"Your profile update request sent to admin.",
    LIFESTORY_UPDATE_REQUESTED:"Your lifestory update request sent to admin.",
    LIFESTORY_ADD_REQUESTED:"Your lifestory add request sent to admin.",
    NOTE_ADD_REQUESTED:"Note added successfully..!",
    NOTE_UPDATE_REQUESTED:"Note updated successfully..!",
    GAME_CREATED_SUCCESSFULLY : "Game created successfully...!",
}